steps:
  - name: gcr.io/k8s-skaffold/skaffold
    args:
      - skaffold
      - build
      - '--interactive=false'
      - '--default-repo=gcr.io/searce-playground-v1/gcr77-test'
      - '--file-output=artifacts.json'
    dir: example
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - '-c'
      - >
        gcloud deploy releases create prajakta-$(date +%y%m%d-%s)
        --delivery-pipeline=demo-clouddeploy --build-artifacts=artifacts.json
        --source=./
        --region=us-central1
    dir: example
    entrypoint: bash
